import type { Metadata } from 'next';
import { Poppins, Inter } from 'next/font/google';
import '@/styles/global.scss';
import TopHeader from '@/components/topheader/TopHeader';
import Header from '@/components/header/Header';

const poppins = Poppins({
  variable: '--poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

const inter = Inter({
  variable: '--inter',
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${inter.variable}`}>
        <TopHeader />
        <Header />
        {children}
      </body>
    </html>
  );
}
